/*
 * Copyright 2011-2023 Mark Injerd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pilot51.lander

object Res {
	enum class ResString(val stringName: String) {
		APP_NAME("app_name"),
		OK("ok"),
		CANCEL("cancel"),
		GAME("game"),
		NEW("new_"),
		RESTART("restart"),
		MAPS("maps"),
		OPTIONS("options"),
		OPTIONS_ELLIPSIS("options_ellipsis"),
		EXIT("exit"),
		ABOUT_LANDER("about_lander"),
		ABOUT("about"),
		ALTITUDE("altitude"),
		VELOCITY_X("velocity_x"),
		VELOCITY_Y("velocity_y"),
		FUEL("fuel"),
		END_SAFE("end_safe"),
		END_CRASH("end_crash"),
		END_CRASHV1("end_crashv1"),
		END_CRASHV2("end_crashv2"),
		END_CRASHV3("end_crashv3"),
		END_CRASHH("end_crashh"),
		END_CRASHA("end_crasha"),
		END_CRASHS("end_crashs"),
		END_OUTOFRANGE("end_outofrange"),
		ABOUT_TEXT("about_text"),
		CLASSIC_OPTIONS("classic_options"),
		GRAVITY("gravity"),
		GRAVITY_SUMMARY("gravity_summary"),
		FUEL_SUMMARY("fuel_summary"),
		THRUST("thrust"),
		THRUST_SUMMARY("thrust_summary"),
		DRAWFLAME("drawflame"),
		REVERSESIDETHRUST("reversesidethrust"),
		DEFAULT_TITLE("default_title"),
		DEFAULT_SUMMARY("default_summary"),
		CLASSIC_OPTIONS_RESET("classic_options_reset"),
		EXTRA_OPTIONS("extra_options"),
		CONTROLS("controls"),
		ONSCREEN_CONTROLS("onscreen_controls"),
		BTN_SCALE("btn_scale"),
		BTN_ALPHA("btn_alpha"),
		KEY_ASSIGNMENTS("key_assignments"),
		CONTROLS_NOKEYS("controls_nokeys"),
		LEFT("left"),
		RIGHT("right"),
		CURRENT_BUTTON("current_button"),
		PRESS_NEW_BUTTON("press_new_button"),
		DEFAULT_CONTROLS_TITLE("default_controls_title"),
		CONTROLS_RESET("controls_reset"),
		IMPROVEMENTS("improvements"),
		IMPROVEMENTS_SUMMARY("improvements_summary"),
		PRESETS("presets"),
		CLASSIC("classic"),
		IMPROVED("improved"),
		INDIVIDUAL_IMP("individual_imp"),
		IMP_END_IMG("imp_end_img"),
		IMP_END_IMG_BW("imp_end_img_bw"),
		IMP_END_IMG_COLOR("imp_end_img_color"),
		IMP_LANDER_ALPHA("imp_lander_alpha"),
		IMP_LANDER_ALPHA_ON("imp_lander_alpha_on"),
		IMP_LANDER_ALPHA_OFF("imp_lander_alpha_off"),
		GAMEPLAY_MOD("gameplay_mod"),
		GAMEPLAY_MOD_SUMMARY("gameplay_mod_summary"),
		INDIVIDUAL_MOD("individual_mod"),
		ROTATION("rotation"),
		ROTATION_SUMMARY("rotation_summary"),
		MAP_LIST("map_list"),
		MAP_LIST_SUMMARY("map_list_summary"),
		MAP_LOADED("map_loaded"),
		MAP_SAVED("map_saved"),
		MAP_REMOVED("map_removed"),
		MAPS_CLEARED("maps_cleared"),
		DLG_CREATE_MAP("dlg_create_map"),
		DLG_EDIT_MAP("dlg_edit_map"),
		DLG_SAVE_MAP("dlg_save_map"),
		INVALID_PLOT("invalid_plot"),
		EDIT("edit"),
		REMOVE("remove"),
		CREATE_MAP("create_map"),
		SAVE_CURRENT("save_current"),
		CLEAR_MAPS("clear_maps"),
		MAP_NAME("map_name"),
		MAP_PLOT("map_plot"),
	}

	enum class ResImage(val fileName: String) {
		BFLAME("bflame"),
		CRASH1("crash1"),
		CRASH2("crash2"),
		CRASH3("crash3"),
		DEAD("dead"),
		DEAD_COLOR("dead_color"),
		EXPL1("expl1"),
		EXPL2("expl2"),
		EXPL3("expl3"),
		EXPL4("expl4"),
		EXPL5("expl5"),
		EXPL6("expl6"),
		EXPL7("expl7"),
		EXPL8("expl8"),
		EXPL9("expl9"),
		EXPL10("expl10"),
		ICON("icon"),
		ILEFT("ileft"),
		IRIGHT("iright"),
		ITHRUST("ithrust"),
		LANDER("lander"),
		LEFT("left"),
		LFLAME("lflame"),
		RFLAME("rflame"),
		RIGHT("right"),
		SAFE("safe"),
		SAFE_COLOR("safe_color"),
		THRUST("thrust")
	}
}
